dataset:
  dataset: srncars
  image_resolution: 128
  data_dimension: 128
  hparams_nerf:
    resolution: 128
    epoch_for_full_rendering: 5
    subsampled_views: 32
    subsampled_pixels: 512
    num_samples_per_ray: 31
    near: 0.8
    far: 1.8
    randomized: True
    prob_mask_sampling: 0.0
    rgb_activation: no_use
    density_activation: elu
    H: 128
    W: 128

stage2:
  hparams_diffusion:
    steps: 1000
    learn_sigma: False
    noise_schedule: squaredcos_cap_v2
    rescale_learned_sigmas: False
    predict_xstart: True

  hparams_model:
    net_type: functa
    num_layers: 8
    num_hid_groups: 16
    num_hid_channels: 4096
    num_channels: 128
    activation: silu

    num_time_layers: 1
    num_time_emb_channels: 64

  feat_type: context
  feat_std_scale: 1.0

  hparams_metainr:
    width: 64
    depth: 4
    w0: 30
    k_mixtures: 256
    latent_channels: 128
    image_resolution: 128
    in_channels: 3
    out_channels: 4
    use_meta_sgd: False
    pred_type: scene

optimizer:
  use_amp: False
  use_ema: True
  opt_type: adamw
  base_lr: 1.0e-4
  grad_clip_norm: 0.0  # means don't clip
  betas: [0.9, 0.999]
  warmup:
    multiplier: 1
    warmup_epoch: 0.0  
    buffer_epoch: 0
    min_lr: 0.0
    mode: fix
    start_from_zero: True

experiment:
  epochs: 1000
  save_ckpt_freq: 1000
